Repository AndyJacko/CN-Master-Shoebill-Frontend, pull requests merged in 2022-11, with the labels that each got.

#21 "added css to post.js"
  src/Components/Login.css
  src/Components/Post.css
  src/Components/Post.js
  src/Components/Register.css
  src/Components/Update.css
Labels: documentation

#39 changes to input size and css
  src/Components/Login.js
  src/Components/Post.css
  src/Components/Post.js
  src/Components/Register.js
  src/Components/Update.js
Labels: bug

#40 Elixium
  src/App.css
  src/Components/Login.js
  src/Components/Post.js
  src/Components/Register.js
  src/Components/Update.js
  src/pages/page-layout/Sidebars/LeftSidebar/LeftSidebar.css
  src/pages/page-layout/Sidebars/LeftSidebar/LeftSidebar.js
Labels: enhancement

#41 canges to css
  src/App.css
  src/Components/Login.js
  src/Components/Post.js
  src/Components/Register.js
  src/Components/Update.js
  src/Components/UserItem/UserItem.css
  src/pages/AllUsers.js
  src/pages/page-layout/Sidebars/LeftSidebar/LeftSidebar.css
  src/pages/page-layout/Sidebars/LeftSidebar/LeftSidebar.js
Labels: documentation

#43 Populate Home Page with live bark data - AJ
  src/Components/HomePageBarkItem/HomePageBarkItem.css
  src/Components/HomePageBarkItem/HomePageBarkItem.js
  src/pages/Home.js
Labels: enhancement

#44 Feature/homepage
  src/Components/HomePageBarkItem/HomePageBarkItem.css
  src/Components/HomePageBarkItem/HomePageBarkItem.js
  src/pages/Home.js
Labels: enhancement

#45 Merging changes to css in css in login and register modals
  src/Components/Login.js
  src/Components/Post.js
  src/Components/Register.js
Labels: documentation

#47 Changes to css and code clean up
  src/Components/HomePageBarkItem/HomePageBarkItem.css
  src/Components/HomePageBarkItem/HomePageBarkItem.js
  src/pages/Home.js
Labels: documentation

#48 fix layout - AJ
  src/App.css
  src/Components/HomePageBarkItem/HomePageBarkItem.css
  src/Components/Latest/Latest.css
  src/Components/UserProfileBarkItem/UserProfileBarkItem.css
  src/Components/UserProfileInfo/UserProfileInfo.css
  src/pages/AllUsers.js
  src/pages/Home.js
  src/pages/Messages.js
  src/pages/NotFound.js
  src/pages/Notifications.js
  src/pages/Profile.js
  src/pages/page-layout/Layout.css
Labels: enhancement

#49 Feature/layout
  src/App.css
  src/Components/HomePageBarkItem/HomePageBarkItem.css
  src/Components/Latest/Latest.css
  src/Components/UserProfileBarkItem/UserProfileBarkItem.css
  src/Components/UserProfileInfo/UserProfileInfo.css
  src/pages/AllUsers.js
  src/pages/Home.js
  src/pages/Messages.js
  src/pages/NotFound.js
  src/pages/Notifications.js
  src/pages/Profile.js
  src/pages/page-layout/Layout.css
Labels: enhancement

#52 Feature/alluserspage
  src/Components/UserItem/UserItem.css
  src/Components/UserItem/UserItem.js
Labels: enhancement

#53 Add login function...
  src/App.js
  src/Components/Latest/Latest.js
  src/Components/Login.js
  src/Components/Post.js
  src/Components/Register.js
  src/pages/Profile.js
  src/pages/page-layout/Layout.js
  src/pages/page-layout/Sidebars/LeftSidebar/LeftSidebar.js
Labels: enhancement

#55 Fix/layouttweaks
  src/App.js
  src/Components/Latest/Latest.css
  src/Components/Latest/Latest.js
  src/Components/Login.js
  src/Components/Post.js
  src/Components/Register.js
  src/Components/UI/Spinner/Spinner.css
  src/Components/UI/Spinner/Spinner.js
  src/Components/Update.js
  src/Components/UserItem/UserItem.css
  src/Components/UserItem/UserItem.js
  src/Components/UserProfileInfo/UserProfileInfo.css
  src/pages/EditProfile.js
  src/pages/Profile.css
  src/pages/Profile.js
  src/pages/page-layout/Layout.js
  src/pages/page-layout/Sidebars/LeftSidebar/LeftSidebar.css
  src/pages/page-layout/Sidebars/LeftSidebar/LeftSidebar.js
Labels: enhancement

#56 Feature/layout
  src/App.js
  src/Components/Latest/Latest.css
  src/Components/Latest/Latest.js
  src/Components/UI/Spinner/Spinner.css
  src/Components/UI/Spinner/Spinner.js
  src/Components/UserProfileInfo/UserProfileInfo.css
  src/pages/EditProfile.js
  src/pages/Profile.css
  src/pages/Profile.js
  src/pages/page-layout/Sidebars/LeftSidebar/LeftSidebar.css
Labels: enhancement

#57 Add save cookie on login, deletecookie on logout, get cookie on app l…
  src/App.js
  src/Components/Login.js
  src/utils/cookies.js
Labels: enhancement

#58 Add Edit User Form - needs linking to api on submit - AJ
  src/App.js
  src/Components/EditProfileForm/EditProfileForm.css
  src/Components/EditProfileForm/EditProfileForm.js
  src/pages/EditProfile.js
Labels: enhancement

#59 Feature/editprofile
  src/App.js
  src/Components/EditProfileForm/EditProfileForm.css
  src/Components/EditProfileForm/EditProfileForm.js
  src/pages/EditProfile.js
Labels: enhancement

#62 Enhancement/editprofiletoapi
  src/Components/EditProfileForm/EditProfileForm.js
Labels: enhancement

#63 Feature/editprofile
  src/Components/EditProfileForm/EditProfileForm.js
Labels: enhancement

#65 Feature/profilepage
  src/Components/HomePageBarkItem/HomePageBarkItem.js
  src/Components/UserItem/UserItem.js
  src/Components/UserProfileInfo/UserProfileInfo.css
  src/Components/UserProfileInfo/UserProfileInfo.js
  src/Components/WhoToFollow/WhoToFollow.js
Labels: enhancement

#66 Register now working with api fully - AJ
  src/Components/Register.js
  src/pages/page-layout/Sidebars/LeftSidebar/LeftSidebar.js
Labels: enhancement

#67 Feature/registeruser
  src/Components/Register.js
  src/pages/page-layout/Sidebars/LeftSidebar/LeftSidebar.js
Labels: enhancement

#68 Fix/removelorem
  src/App.js
  src/Components/EditProfileForm/EditProfileForm.css
  src/Components/EditProfileForm/EditProfileForm.js
  src/Components/HomePageBarkItem/HomePageBarkItem.js
  src/Components/Latest/Latest.css
  src/Components/Latest/Latest.js
  src/Components/Login.js
  src/Components/Post.js
  src/Components/Register [Backup].js
  src/Components/Register.js
  src/Components/UI/Spinner/Spinner.css
  src/Components/UI/Spinner/Spinner.js
  src/Components/UserItem/UserItem.js
  src/Components/UserProfileInfo/UserProfileInfo.css
  src/Components/UserProfileInfo/UserProfileInfo.js
  src/Components/WhoToFollow/WhoToFollow.js
  src/pages/EditProfile.js
  src/pages/Profile.css
  src/pages/Profile.js
  src/pages/page-layout/Layout.js
  src/pages/page-layout/Sidebars/LeftSidebar/LeftSidebar.css
  src/pages/page-layout/Sidebars/LeftSidebar/LeftSidebar.js
  src/utils/cookies.js
Labels: enhancement

#71 Feature/createpost
  src/Components/Post.js
  src/pages/page-layout/Sidebars/LeftSidebar/LeftSidebar.js
Labels: enhancement

#72 Update delete user button to api - AJ
  src/App.js
  src/Components/Post.js
  src/pages/Home.js
  src/pages/Profile.js
Labels: enhancement

#73 Feature/deleteuser
  src/App.js
  src/Components/Post.js
  src/pages/Home.js
  src/pages/Profile.js
Labels: enhancement

#74 Enhancement/autologin
  src/App.js
  src/Components/EditProfileForm/EditProfileForm.css
  src/Components/EditProfileForm/EditProfileForm.js
  src/Components/HomePageBarkItem/HomePageBarkItem.js
  src/Components/Latest/Latest.css
  src/Components/Latest/Latest.js
  src/Components/Login.js
  src/Components/Post.js
  src/Components/Register [Backup].js
  src/Components/Register.js
  src/Components/UI/Spinner/Spinner.css
  src/Components/UI/Spinner/Spinner.js
  src/Components/UserItem/UserItem.js
  src/Components/UserProfileInfo/UserProfileInfo.css
  src/Components/UserProfileInfo/UserProfileInfo.js
  src/Components/WhoToFollow/WhoToFollow.js
  src/pages/EditProfile.js
  src/pages/Home.js
  src/pages/Profile.css
  src/pages/Profile.js
  src/pages/page-layout/Sidebars/LeftSidebar/LeftSidebar.css
  src/pages/page-layout/Sidebars/LeftSidebar/LeftSidebar.js
  src/utils/cookies.js
Labels: enhancement

#75 Feature/login
  src/App.js
Labels: enhancement

#77 Add delete post function to home page posts and user profile posts - AJ
  src/App.js
  src/Components/HomePageBarkItem/HomePageBarkItem.css
  src/Components/HomePageBarkItem/HomePageBarkItem.js
  src/Components/UserProfileBarkItem/UserProfileBarkItem.js
  src/pages/Home.js
  src/pages/Profile.js
Labels: enhancement

#78 Feature/deletepost
  src/App.js
  src/Components/HomePageBarkItem/HomePageBarkItem.css
  src/Components/HomePageBarkItem/HomePageBarkItem.js
  src/Components/UserProfileBarkItem/UserProfileBarkItem.js
  src/pages/Home.js
  src/pages/Profile.js
Labels: enhancement

#79 Add like function added to home page posts and user profile posts - AJ
  src/Components/HomePageBarkItem/HomePageBarkItem.css
  src/Components/HomePageBarkItem/HomePageBarkItem.js
  src/Components/UserProfileBarkItem/UserProfileBarkItem.js
  src/pages/Home.js
  src/pages/Profile.js
Labels: enhancement

#80 Feature/addlikes
  src/Components/HomePageBarkItem/HomePageBarkItem.css
  src/Components/HomePageBarkItem/HomePageBarkItem.js
  src/Components/UserProfileBarkItem/UserProfileBarkItem.js
  src/pages/Home.js
  src/pages/Profile.js
Labels: enhancement

#81 Fix page return to top of page on load - AJ
  src/pages/AllUsers.js
  src/pages/EditProfile.js
  src/pages/Messages.js
  src/pages/Notifications.js
  src/pages/Profile.js
Labels: enhancement

#82 Enhancement/postimage
  src/Components/HomePageBarkItem/HomePageBarkItem.css
  src/pages/AllUsers.js
  src/pages/EditProfile.js
  src/pages/Messages.js
  src/pages/Notifications.js
  src/pages/Profile.js
Labels: enhancement

#84 Add environment vars in place of API URL - AJ
  src/App.js
  src/Components/EditProfileForm/EditProfileForm.js
  src/Components/HomePageBarkItem/HomePageBarkItem.js
  src/Components/Login.js
  src/Components/Post.js
  src/Components/Register.js
  src/Components/UserProfileBarkItem/UserProfileBarkItem.js
  src/pages/AllUsers.js
  src/pages/Home.js
  src/pages/Profile.js
  src/pages/page-layout/Sidebars/RightSidebar/RightSidebar.js
Labels: enhancement

#85 Feature/envvars
  src/App.js
  src/Components/EditProfileForm/EditProfileForm.js
  src/Components/HomePageBarkItem/HomePageBarkItem.js
  src/Components/Login.js
  src/Components/Post.js
  src/Components/Register.js
  src/Components/UserProfileBarkItem/UserProfileBarkItem.js
  src/pages/AllUsers.js
  src/pages/Home.js
  src/pages/Profile.js
  src/pages/page-layout/Sidebars/RightSidebar/RightSidebar.js
Labels: enhancement
